In [33]:
import torch
import numpy as np

# Tensori

In [62]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [63]:
t2 = torch.tensor([1., 2, 3, 4])
#NB! Tutti i dati di un tensore hanno sempre lo stesso tipo, in questo caso anche gli int diventano dei float

In [64]:
t3 =torch.tensor([[5., 6],
                  [7, 8],
                  [9, 10]
                ])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [65]:
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19]]
])
t4

#crea una matrice tridimensionale 2x2x3 (2 "strati", 2 righe [righe in ogni strato], 3 colonne [elementi all'interno di ogni riga])

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [66]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [67]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [68]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [69]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

In [70]:
# NB! NON si possono creare tensori con shape non definiti, ossia non si possono lasciare "spazi vuoti", se la prima riga
# è [1, 2, 3] la seconda non può essere ad esempio [5, 6] perché mancherebbe un elemento per completare la riga

In [71]:
xt = torch.tensor (3. )
wt = torch. tensor (4., requires_grad =True)
bt = torch.tensor (5., requires_grad = True)
xt, wt, bt

# requires_grad =True specifica che siamo interessati a calcolare le derivate di questa variabile all'interno del programma
# se non lo mettiamo il programma non calcolerà mai la derivata rispetto quella determinata variabile

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [72]:
yt = wt * xt + bt
yt

tensor(17., grad_fn=<AddBackward0>)

In [73]:
yt.backward()

#esegue la derivata del tensore e salva i risultati all'interno della proprietà .grad del tensore

In [74]:
print('dy/dx: ', xt.grad)
print('dy/dw: ', wt.grad)
print('dy/db: ', bt.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [75]:
t6 = torch.full((3,2), 11)
t6

# torch.full((shape), num che inserisce)        serve a riempire un tensore con un numero specificando una shape

tensor([[11, 11],
        [11, 11],
        [11, 11]])

In [76]:
t7 = torch.cat((t3, t6))
t7

# torch.cat((tensore1, tensore2))       permette di concatenare due tensori NB! devono avere shape compatibili

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 11.],
        [11., 11.],
        [11., 11.]])

In [77]:
t8 = torch.sin(t7)
t8

# torch.sin(tensore)     calcola il seno di ogni valore nel tensore

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-1.0000, -1.0000],
        [-1.0000, -1.0000],
        [-1.0000, -1.0000]])

In [78]:
t9 = t8.reshape(3, 2, 2)
t9

# tensore.reshape(3, 2, 2)      permette di assegnare una nuova shape a un tensore NB! devono essere compatibili il numero di dati

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-1.0000, -1.0000]],

        [[-1.0000, -1.0000],
         [-1.0000, -1.0000]]])

# Numpy

In [79]:
a = np.array([[1,2],
              [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [80]:
b = torch.from_numpy(x)
b

# torch.from_numpy(var_numpy)       trasforma un vettore numpy in un tensore torch

tensor([[1, 2],
        [3, 4]])

In [81]:
c = b.numpy()
c

# tensore.numpy()       trasforma un tensore in un array numpy

array([[1, 2],
       [3, 4]])

# Regressione lineare

In una regressione lineare ogni target è stimato da una somma pesata delle variabili in input a cui è sommata una distorsione detta bias
Il training della regressione lineare avviene tramite il settaggio dei pesi e dei bias affinchè la predizione di nuove informazioni sia accurata

In [88]:
# Input (temp, precipitazioni, umidità)

inputs = np.array([[72, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]],
                   dtype = 'float32'
                  )

In [89]:
# Targets (mele, arance)

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]],
                    dtype = 'float32'
                   )

Solitamente i dati vengono importati da file csv in array numpy che vengono processati e infine convertiti in PyTorch

In [90]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 72.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [99]:
pesi = torch.randn(2, 3, requires_grad = True)
bias = torch.randn(2, requires_grad = True)

# torch.randn(shape, requires_grad = True)      crea un tensore con la shape data con elementi random che hanno una distribuzione normalizzata

print(pesi)
print(bias)

tensor([[-1.0653,  0.9042,  0.4845],
        [ 0.3961, -0.4913, -0.0550]], requires_grad=True)
tensor([-0.6903,  0.5657], requires_grad=True)


Funzione che fa una predizione delle variabili target in base agli input dati

In [96]:
def model(x):
    return x @ pesi.t() + bias

# @ moltiplicazione matriciale in PyTorch
# .t metodo che fa la trasposta del tensore

In [102]:
pred = model(inputs)
print(pred)

tensor([[  4.0227,  -6.1983],
        [ 12.9450, -10.1451],
        [ 55.8927, -34.0000],
        [-52.5454,  17.8062],
        [ 46.5232, -23.1198]], grad_fn=<AddBackward0>)
